# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

import send as sd

id = sd.username('Jackson')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CaixadeMensagem = QtWidgets.QTabWidget(self.centralwidget)
        self.CaixadeMensagem.setObjectName("CaixadeMensagem")
        self.receMail = QtWidgets.QWidget()
        self.receMail.setObjectName("receMail")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.receMail)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listView = QtWidgets.QListView(self.receMail)
        self.listView.setObjectName("listView")
        self.verticalLayout_3.addWidget(self.listView)
        self.pushButton_4 = QtWidgets.QPushButton(self.receMail)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.CaixadeMensagem.addTab(self.receMail, "")
        self.redMail = QtWidgets.QWidget()
        self.redMail.setObjectName("redMail")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.redMail)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.redMail)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.CaixadeMensagem.addTab(self.redMail, "")
        self.sendMail = QtWidgets.QWidget()
        self.sendMail.setObjectName("sendMail")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sendMail)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.sendMail)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.sendMail)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.sendMail)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.sendMail)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.sendMail)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.sendMail)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.textEdit = QtWidgets.QTextEdit(self.sendMail)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.sendMail)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.sendMail)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.sendMail)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.CaixadeMensagem.addTab(self.sendMail, "")
        self.verticalLayout.addWidget(self.CaixadeMensagem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionSobre_Qt = QtWidgets.QAction(MainWindow)
        self.actionSobre_Qt.setObjectName("actionSobre_Qt")
        self.actionSair_2 = QtWidgets.QAction(MainWindow)
        self.actionSair_2.setObjectName("actionSair_2")
        self.menuArquivo.addAction(self.actionSair)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair_2)
        self.menuAjuda.addAction(self.actionSobre)
        self.menuAjuda.addAction(self.actionSobre_Qt)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.CaixadeMensagem.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyMail"))
        self.pushButton_4.setText(_translate("MainWindow", "Atualizar"))
        self.CaixadeMensagem.setTabText(self.CaixadeMensagem.indexOf(self.receMail), _translate("MainWindow", "Caixa de Mensagem"))
        self.CaixadeMensagem.setTabText(self.CaixadeMensagem.indexOf(self.redMail), _translate("MainWindow", "Ler E-mail"))
        self.label.setText(_translate("MainWindow", "De:"))
        self.label_2.setText(_translate("MainWindow", "Para:"))
        self.label_3.setText(_translate("MainWindow", "Assunto:"))
        self.pushButton.setText(_translate("MainWindow", "Anexos"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancelar"))
        self.pushButton_3.setText(_translate("MainWindow", "Enviar"))
        self.CaixadeMensagem.setTabText(self.CaixadeMensagem.indexOf(self.sendMail), _translate("MainWindow", "Enviar E-mail"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda"))
        self.actionSair.setText(_translate("MainWindow", "Configurações"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionSobre_Qt.setText(_translate("MainWindow", "Sobre Qt"))
        self.actionSair_2.setText(_translate("MainWindow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

